name: Inkstained
favicon: null
layout_spectrum: 0.3820631974376738
typography_spectrum: 0.3835100154392421
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.786410189466551
  lightness: 0.13063694653101265
  saturation: 0.23027527518570423
  rhythmicContrast: 0.7671872589271516
purpose: []
